### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'logging_dir'

### ISSUE THREAD

**Issue by SongChaotian** [mkshing/svdiff-pytorch#12]
I got this error "TypeError: __init__() got an unexpected keyword argument 'logging_dir'" while executing the following command and would like to ask how to solve it:

export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export INSTANCE_DIR="images/dog/instance"
export CLASS_DIR="images/dog/class"
export OUTPUT_DIR="output_models"

accelerate launch train_svdiff.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="photo of a sks dog" \
  --class_prompt="photo of a dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-3 \
  --learning_rate_1d=1e-6 \
  --train_text_encoder \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=500

**Comment by CloudWalking0** [comment]
> I got this error "TypeError: **init**() got an unexpected keyword argument 'logging_dir'" while executing the following command and would like to ask how to solve it:
> 
> export MODEL_NAME="runwayml/stable-diffusion-v1-5" export INSTANCE_DIR="images/dog/instance" export CLASS_DIR="images/dog/class" export OUTPUT_DIR="output_models"
> 
> accelerate launch train_svdiff.py --pretrained_model_name_or_path=$MODEL_NAME --instance_data_dir=$INSTANCE_DIR --class_data_dir=$CLASS_DIR --output_dir=$OUTPUT_DIR --with_prior_preservation --prior_loss_weight=1.0 --instance_prompt="photo of a sks dog" --class_prompt="photo of a dog" --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=1e-3 --learning_rate_1d=1e-6 --train_text_encoder --lr_scheduler="constant" --lr_warmup_steps=0 --num_class_images=200 --max_train_steps=500

Hi, this bug caused by the version of "accelerate", the new release use "project_dir" instead of "logging_dir". So you can try to modify the definition of 'accelerator' like this:
`accelerator = Accelerator(
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        mixed_precision=args.mixed_precision,
        log_with=args.report_to,
        project_dir=logging_dir,
        project_config=accelerator_project_config,
    )`

**Comment by SongChaotian** [comment]
您发给我的信件已经收到，感谢您的配合，辛苦了。

**Comment by SongChaotian** [comment]
> > I got this error "TypeError: **init**() got an unexpected keyword argument 'logging_dir'" while executing the following command and would like to ask how to solve it:
> > export MODEL_NAME="runwayml/stable-diffusion-v1-5" export INSTANCE_DIR="images/dog/instance" export CLASS_DIR="images/dog/class" export OUTPUT_DIR="output_models"
> > accelerate launch train_svdiff.py --pretrained_model_name_or_path=$MODEL_NAME --instance_data_dir=$INSTANCE_DIR --class_data_dir=$CLASS_DIR --output_dir=$OUTPUT_DIR --with_prior_preservation --prior_loss_weight=1.0 --instance_prompt="photo of a sks dog" --class_prompt="photo of a dog" --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=1e-3 --learning_rate_1d=1e-6 --train_text_encoder --lr_scheduler="constant" --lr_warmup_steps=0 --num_class_images=200 --max_train_steps=500
> 
> Hi, this bug caused by the version of "accelerate", the new release use "project_dir" instead of "logging_dir". So you can try to modify the definition of 'accelerator' like this: `accelerator = Accelerator( gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision, log_with=args.report_to, project_dir=logging_dir, project_config=accelerator_project_config, )`

Hi, I have tried according to your method and successfully solved the problem, thank you
